name: empatica_ppg_artifact_detection
description: "PPG artifact detection based on IBI and signal quality metrics"

steps:

  - input_data_types: ["EMP_BVP_ibi", "EMP_BVP_quality"]
    output_data_types: ["EMP_BVP_artifact"]
    transforms:
      - transform: PPGArtifactLabels
        config:
          segment_duration: 30
          quality_threshold: 0.8
          ibi_range: [300, 2000]  # Valid IBI range in ms
          min_valid_ratio: 0.5  # Minimum ratio of valid samples in segment

  - input_data_types: ["annotations", "EMP_BVP_artifact"]
    output_data_types: ["annotations"]
    transforms:
      - transform: MergeArtifactLabels
