name: simple_ppg_processing
description: "Basic PPG processing pipeline with filtering and resampling"

steps:
  - input_data_types: ["PPG"]
    output_data_types: ["PPG_filtered"]
    transforms:
      - transform: FIRFilter
        config:
          low_cutoff: 0.5
          high_cutoff: 8.0
  
  - input_data_types: ["PPG_filtered"]
    output_data_types: ["PPG_resampled"]
    transforms:
      - transform: Resample
        config:
          new_sample_rate: 128.0
